const BooksListActionTypes = {
    SET_LIST_OF_BOOKS : 'SET_LIST_OF_BOOKS',
    SET_BOOK_SEARCH_QUERY : 'SET_BOOK_SEARCH_QUERY',
    SET_SELECTED_AUTHOR_ID : 'SET_SELECTED_AUTHOR_ID',
    APPEND_TO_LIST_OF_BOOKS : 'APPEND_TO_LIST_OF_BOOKS',
}

export default BooksListActionTypes;
